USE master

CREATE DATABASE esunAssignment
GO

USE esunAssignment

-- SeatingChart
CREATE TABLE SeatingChart (
    FLOOR_SEAT_SEQ INT PRIMARY KEY,
    FLOOR_NO INT NOT NULL,
    SEAT_NO INT NOT NULL
)

-- Employee
CREATE TABLE Employee (
    EMP_ID CHAR(5) PRIMARY KEY,
    NAME NVARCHAR(25) NOT NULL,
    EMAIL NVARCHAR(30) NOT NULL,
    FLOOR_SEAT_SEQ INT,
    FOREIGN KEY (FLOOR_SEAT_SEQ) REFERENCES SeatingChart(FLOOR_SEAT_SEQ)
);

-- 在MSSQL，只創建針對非NULL值唯一鍵，先在資料庫預防不同人重複訂到同一個位置
CREATE UNIQUE NONCLUSTERED INDEX UQ_FLOOR_SEAT_SEQ ON Employee(FLOOR_SEAT_SEQ) 
WHERE FLOOR_SEAT_SEQ IS NOT NULL;